# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-08 13:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('mobile', models.BigIntegerField(help_text='\u7528\u4e8e\u624b\u673a\u9a8c\u8bc1\u7801\u767b\u5f55', null=True, unique=True, verbose_name='\u624b\u673a')),
                ('qq', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='QQ')),
                ('weixin', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='\u5fae\u4fe1')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e2a\u4eba\u7b7e\u540d')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('openid', models.CharField(blank=True, max_length=128, null=True)),
                ('alipay_card', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u652f\u4ed8\u5b9d\u8d26\u6237')),
                ('gender', models.SmallIntegerField(choices=[(0, '\u4fdd\u5bc6'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('id_card', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u6216\u62a4\u7167\u53f7')),
                ('password', models.CharField(help_text="<a class='btn-link' href='password'>\u91cd\u7f6e\u5bc6\u7801</a>", max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u8d26\u6237\u72b6\u6001')),
                ('is_staff', models.BooleanField(default=False, help_text='\u51b3\u5b9a\u7740\u7528\u6237\u662f\u5426\u53ef\u767b\u5f55\u7ba1\u7406\u540e\u53f0', verbose_name='staff status')),
                ('name', models.CharField(default='', max_length=32, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('head_img', models.CharField(default='/static/frontend/head_portrait/logo@2x.png', max_length=256, verbose_name='\u4e2a\u4eba\u5934\u50cf')),
                ('role', models.SmallIntegerField(choices=[(0, '\u5b66\u5458'), (1, '\u5bfc\u5e08'), (2, '\u8bb2\u5e08'), (3, '\u7ba1\u7406\u5458'), (4, '\u73ed\u4e3b\u4efb'), (5, '\u7ebf\u4e0b\u73ed\u4e3b\u4efb')], default=0, verbose_name='\u89d2\u8272')),
                ('memo', models.TextField(blank=True, default=None, help_text='json\u683c\u5f0f\u5b58\u50a8', null=True, verbose_name='\u5907\u6ce8')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('beli', models.IntegerField(default=1000)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u6d3b\u52a8\u540d\u79f0')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='\u4f18\u60e0\u5238\u4ecb\u7ecd')),
                ('coupon_type', models.SmallIntegerField(choices=[(0, '\u7acb\u51cf\u5238'), (1, '\u6ee1\u51cf\u5238'), (2, '\u6298\u6263\u5238')], default=0, verbose_name='\u5238\u7c7b\u578b')),
                ('money_equivalent_value', models.FloatField(blank=True, null=True, verbose_name='\u7b49\u503c\u8d27\u5e01')),
                ('off_percent', models.PositiveSmallIntegerField(blank=True, help_text='\u53ea\u9488\u5bf9\u6298\u6263\u5238\uff0c\u4f8b7.9\u6298\uff0c\u519979', null=True, verbose_name='\u6298\u6263\u767e\u5206\u6bd4')),
                ('minimum_consume', models.PositiveIntegerField(default=0, help_text='\u4ec5\u5728\u6ee1\u51cf\u5238\u65f6\u586b\u5199\u6b64\u5b57\u6bb5', verbose_name='\u6700\u4f4e\u6d88\u8d39')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='\u53ef\u4ee5\u628a\u4f18\u60e0\u5238\u8ddf\u8bfe\u7a0b\u7ed1\u5b9a', null=True, verbose_name='\u7ed1\u5b9a\u8bfe\u7a0b')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='\u6570\u91cf(\u5f20)')),
                ('open_date', models.DateField(verbose_name='\u4f18\u60e0\u5238\u9886\u53d6\u5f00\u59cb\u65f6\u95f4')),
                ('close_date', models.DateField(verbose_name='\u4f18\u60e0\u5238\u9886\u53d6\u7ed3\u675f\u65f6\u95f4')),
                ('valid_begin_date', models.DateField(blank=True, null=True, verbose_name='\u6709\u6548\u671f\u5f00\u59cb\u65f6\u95f4')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='\u6709\u6548\u7ed3\u675f\u65f6\u95f4')),
                ('coupon_valid_days', models.PositiveIntegerField(blank=True, help_text='\u81ea\u5238\u88ab\u9886\u65f6\u5f00\u59cb\u7b97\u8d77', null=True, verbose_name='\u4f18\u60e0\u5238\u6709\u6548\u671f\uff08\u5929\uff09')),
                ('status', models.SmallIntegerField(choices=[(0, '\u4e0a\u7ebf'), (1, '\u4e0b\u7ebf')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u4f7f\u7528'), (1, '\u5df2\u4f7f\u7528'), (2, '\u5df2\u8fc7\u671f'), (3, '\u672a\u9886\u53d6')], default=0)),
                ('get_time', models.DateTimeField(blank=True, help_text='\u7528\u6237\u9886\u53d6\u65f6\u95f4', null=True, verbose_name='\u9886\u53d6\u65f6\u95f4')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4f7f\u7528\u65f6\u95f4')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f7f\u7528\u8005')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u6a21\u5757')),
                ('course_img', models.CharField(max_length=255)),
                ('course_type', models.SmallIntegerField(choices=[(0, '\u4ed8\u8d39'), (1, 'VIP\u4e13\u4eab'), (2, '\u5b66\u4f4d\u8bfe\u7a0b')])),
                ('brief', models.TextField(max_length=2048, verbose_name='\u8bfe\u7a0b\u6982\u8ff0')),
                ('level', models.SmallIntegerField(choices=[(0, '\u521d\u7ea7'), (1, '\u4e2d\u7ea7'), (2, '\u9ad8\u7ea7')], default=1)),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('period', models.PositiveIntegerField(default=7, verbose_name='\u5efa\u8bae\u5b66\u4e60\u5468\u671f(days)')),
                ('order', models.IntegerField(help_text='\u4ece\u4e0a\u4e00\u4e2a\u8bfe\u7a0b\u6570\u5b57\u5f80\u540e\u6392', verbose_name='\u8bfe\u7a0b\u987a\u5e8f')),
                ('attachment_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8bfe\u4ef6\u8def\u5f84')),
                ('status', models.SmallIntegerField(choices=[(0, '\u4e0a\u7ebf'), (1, '\u4e0b\u7ebf'), (2, '\u9884\u4e0a\u7ebf')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.SmallIntegerField(default=1, verbose_name='\u7b2c\u51e0\u7ae0')),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='\u7ae0\u8282\u4ecb\u7ecd')),
                ('is_create', models.BooleanField(default=True, verbose_name='\u662f\u5426\u521b\u5efa\u9898\u5e93\u8fdb\u5ea6')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursechapters', to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='\u8bfe\u65f6')),
                ('course_slogan', models.CharField(blank=True, max_length=125, null=True)),
                ('video_brief_link', models.CharField(blank=True, max_length=255, null=True)),
                ('why_study', models.TextField(verbose_name='\u4e3a\u4ec0\u4e48\u5b66\u4e60\u8fd9\u95e8\u8bfe\u7a0b')),
                ('what_to_study_brief', models.TextField(verbose_name='\u6211\u5c06\u5b66\u5230\u54ea\u4e9b\u5185\u5bb9')),
                ('career_improvement', models.TextField(verbose_name='\u6b64\u9879\u76ee\u5982\u4f55\u6709\u52a9\u4e8e\u6211\u7684\u804c\u4e1a\u751f\u6daf')),
                ('prerequisite', models.TextField(max_length=1024, verbose_name='\u8bfe\u7a0b\u5148\u4fee\u8981\u6c42')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('recommend_courses', models.ManyToManyField(blank=True, related_name='recommend_by', to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField(help_text='\u5efa\u8bae\u6bcf\u4e2a\u8bfe\u65f6\u4e4b\u95f4\u7a7a1\u81f32\u4e2a\u503c\uff0c\u4ee5\u5907\u540e\u7eed\u63d2\u5165\u8bfe\u65f6', verbose_name='\u8bfe\u65f6\u6392\u5e8f')),
                ('section_type', models.SmallIntegerField(choices=[(0, '\u6587\u6863'), (1, '\u7ec3\u4e60'), (2, '\u89c6\u9891')], default=2)),
                ('section_link', models.CharField(blank=True, help_text='\u82e5\u662fvideo\uff0c\u586bvid,\u82e5\u662f\u6587\u6863\uff0c\u586blink', max_length=255, null=True)),
                ('video_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u89c6\u9891\u65f6\u957f')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('free_trail', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u8bd5\u770b')),
                ('is_flash', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4f7f\u7528FLASH\u64ad\u653e')),
                ('player', models.SmallIntegerField(choices=[(0, 'CC'), (1, 'POLYV'), (2, 'ALI')], default=1, help_text='\u89c6\u9891\u64ad\u653e\u5668\u9009\u62e9')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesection', to='api.CourseChapter')),
            ],
        ),
        migrations.CreateModel(
            name='OftenAskedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=1024)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.SmallIntegerField(choices=[(0, '\u5fae\u4fe1'), (1, '\u652f\u4ed8\u5b9d'), (2, '\u4f18\u60e0\u7801'), (3, '\u8d1d\u91cc'), (4, '\u94f6\u8054')])),
                ('payment_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u652f\u4ed8\u7b2c3\u65b9\u8ba2\u5355\u53f7')),
                ('order_number', models.CharField(max_length=128, unique=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('actual_amount', models.FloatField(verbose_name='\u5b9e\u4ed8\u91d1\u989d')),
                ('status', models.SmallIntegerField(choices=[(0, '\u4ea4\u6613\u6210\u529f'), (1, '\u5f85\u652f\u4ed8'), (2, '\u9000\u8d39\u7533\u8bf7\u4e2d'), (3, '\u5df2\u9000\u8d39'), (4, '\u4e3b\u52a8\u53d6\u6d88'), (5, '\u8d85\u65f6\u53d6\u6d88')], verbose_name='\u72b6\u6001')),
                ('order_type', models.SmallIntegerField(choices=[(0, '\u7528\u6237\u4e0b\u5355'), (1, '\u7ebf\u4e0b\u73ed\u521b\u5efa')], default=0, verbose_name='\u8ba2\u5355\u7c7b\u578b')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u8ba2\u5355\u751f\u6210\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8ba2\u5355\u53d6\u6d88\u65f6\u95f4')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('original_price', models.FloatField(verbose_name='\u8bfe\u7a0b\u539f\u4ef7')),
                ('price', models.FloatField(verbose_name='\u6298\u540e\u4ef7\u683c')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_period_display', models.CharField(max_length=32, verbose_name='\u6709\u6548\u671f\u663e\u793a')),
                ('valid_period', models.PositiveIntegerField(verbose_name='\u6709\u6548\u671f(days)')),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('valid_period', models.SmallIntegerField(choices=[(1, '1\u5929'), (3, '3\u5929'), (7, '1\u5468'), (14, '2\u5468'), (30, '1\u4e2a\u6708'), (60, '2\u4e2a\u6708'), (90, '3\u4e2a\u6708'), (120, '4\u4e2a\u6708'), (180, '6\u4e2a\u6708'), (210, '12\u4e2a\u6708'), (540, '18\u4e2a\u6708'), (720, '24\u4e2a\u6708'), (722, '24\u4e2a\u6708'), (723, '24\u4e2a\u6708')])),
                ('price', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('role', models.SmallIntegerField(choices=[(0, '\u8bb2\u5e08'), (1, '\u5bfc\u5e08')], default=0)),
                ('title', models.CharField(max_length=64, verbose_name='\u804c\u4f4d\u3001\u804c\u79f0')),
                ('signature', models.CharField(blank=True, help_text='\u5bfc\u5e08\u7b7e\u540d', max_length=255, null=True)),
                ('image', models.CharField(max_length=128)),
                ('brief', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='teachers',
            field=models.ManyToManyField(to='api.Teacher', verbose_name='\u8bfe\u7a0b\u8bb2\u5e08'),
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order', verbose_name='\u5173\u8054\u8ba2\u5355'),
        ),
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together=set([('content_type', 'object_id', 'valid_period')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('order', 'content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='oftenaskedquestion',
            unique_together=set([('content_type', 'object_id', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set([('chapter', 'section_link')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursechapter',
            unique_together=set([('course', 'chapter')]),
        ),
    ]
